PROJECT:
 - F10

SEARCH_PATH:
 - D:\output

VERSION_HEADER_FILE:
 - __version__.h

VERSION_RE:
 - '\d.\d.\d.\d'
 
OUTPUT_PATH:
 - D:\output

BOOTLOADER:
 - '*.bin'

PARTITION_TABLE:
 - '*.bin'

KERNEL:
 - '*.bin'

FS:
 - '*.bin'

RELEASE:
 - '*.bin'
 - '*.hex'

DEBUG:
 - '*.axf'
 - '*.elf'
 - '*.map'

OTA:
 - '*.bin'

# sub project 
---
SUB1_PROJECT:

SUB1_SEARCH_PATH:

SUB1_VERSION_HEADER_FILE:

SUB1_OUTPUT_PATH:

SUB1_BOOTLOADER:

SUB1_PARTITION_TABLE:

SUB1_KERNEL:

SUB1_FS:

SUB1_RELEASE:

SUB1_DEBUG:

SUB1_OTA:
